services:
  java-service-dev:
    image: maven:3.9-eclipse-temurin-21
    container_name: java-service-dev
    working_dir: /app

    volumes:
      - /var/www/java-service:/app
      - java-service-maven-cache:/root/.m2

    command: mvn spring-boot:run -Dspring-boot.run.profiles=dev

    ports:
      - "0.0.0.0:18081:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev

    restart: unless-stopped

volumes:
  java-service-maven-cache:
